version: '3.3'

services:
  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: plugga
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build: ./backend
    ports:
      - "5000:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules: