version: '3.7'

services:
  db:
    build: ./db
    container_name: plugga_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: plugga
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/backend
    depends_on:
      - db
    restart: on-failure


  frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/frontend-dev.env

volumes:
  node-modules: