version: '3.7'

services:
  db:
    build: ./db
    ports:
      - "3306:3306"
    container_name: plugga_db
    restart: always
    env_file:
      - ./db/db-dev.env

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/backend
    depends_on:
      - db
    restart: on-failure
    env_file:
      - ./backend/backend-dev.env

  frontend:
    build: ./frontend
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    env_file:
      - ./frontend/frontend-dev.env